<?php

$pluginsDir = dirname(__DIR__);

return [
    'phpList\plugin\SubscribersPlugin\CbgConverter' => $pluginsDir . '/SubscribersPlugin/CbgConverter.php',
    'phpList\plugin\SubscribersPlugin\Command\Add' => $pluginsDir . '/SubscribersPlugin/Command/Add.php',
    'phpList\plugin\SubscribersPlugin\Command\Base' => $pluginsDir . '/SubscribersPlugin/Command/Base.php',
    'phpList\plugin\SubscribersPlugin\Command\Blacklist' => $pluginsDir . '/SubscribersPlugin/Command/Blacklist.php',
    'phpList\plugin\SubscribersPlugin\Command\Confirm' => $pluginsDir . '/SubscribersPlugin/Command/Confirm.php',
    'phpList\plugin\SubscribersPlugin\Command\Delete' => $pluginsDir . '/SubscribersPlugin/Command/Delete.php',
    'phpList\plugin\SubscribersPlugin\Command\EmptyAttribute' => $pluginsDir . '/SubscribersPlugin/Command/EmptyAttribute.php',
    'phpList\plugin\SubscribersPlugin\Command\Factory' => $pluginsDir . '/SubscribersPlugin/Command/Factory.php',
    'phpList\plugin\SubscribersPlugin\Command\Move' => $pluginsDir . '/SubscribersPlugin/Command/Move.php',
    'phpList\plugin\SubscribersPlugin\Command\Remove' => $pluginsDir . '/SubscribersPlugin/Command/Remove.php',
    'phpList\plugin\SubscribersPlugin\Command\RemoveAll' => $pluginsDir . '/SubscribersPlugin/Command/RemoveAll.php',
    'phpList\plugin\SubscribersPlugin\Command\Resend' => $pluginsDir . '/SubscribersPlugin/Command/Resend.php',
    'phpList\plugin\SubscribersPlugin\Command\ResetBounceCount' => $pluginsDir . '/SubscribersPlugin/Command/ResetBounceCount.php',
    'phpList\plugin\SubscribersPlugin\Command\SubscribePage' => $pluginsDir . '/SubscribersPlugin/Command/SubscribePage.php',
    'phpList\plugin\SubscribersPlugin\Command\Unblacklist' => $pluginsDir . '/SubscribersPlugin/Command/Unblacklist.php',
    'phpList\plugin\SubscribersPlugin\Command\Unconfirm' => $pluginsDir . '/SubscribersPlugin/Command/Unconfirm.php',
    'phpList\plugin\SubscribersPlugin\ControllerFactory' => $pluginsDir . '/SubscribersPlugin/ControllerFactory.php',
    'phpList\plugin\SubscribersPlugin\Controller\Command' => $pluginsDir . '/SubscribersPlugin/Controller/Command.php',
    'phpList\plugin\SubscribersPlugin\Controller\Details' => $pluginsDir . '/SubscribersPlugin/Controller/Details.php',
    'phpList\plugin\SubscribersPlugin\Controller\Domains' => $pluginsDir . '/SubscribersPlugin/Controller/Domains.php',
    'phpList\plugin\SubscribersPlugin\Controller\History' => $pluginsDir . '/SubscribersPlugin/Controller/History.php',
    'phpList\plugin\SubscribersPlugin\Controller\Import2' => $pluginsDir . '/SubscribersPlugin/Controller/Import2.php',
    'phpList\plugin\SubscribersPlugin\Controller\Inactive' => $pluginsDir . '/SubscribersPlugin/Controller/Inactive.php',
    'phpList\plugin\SubscribersPlugin\Controller\Reports' => $pluginsDir . '/SubscribersPlugin/Controller/Reports.php',
    'phpList\plugin\SubscribersPlugin\Controller\Simplereport' => $pluginsDir . '/SubscribersPlugin/Controller/Simplereport.php',
    'phpList\plugin\SubscribersPlugin\Controller\Subscriptions' => $pluginsDir . '/SubscribersPlugin/Controller/Subscriptions.php',
    'phpList\plugin\SubscribersPlugin\DAO\Command' => $pluginsDir . '/SubscribersPlugin/DAO/Command.php',
    'phpList\plugin\SubscribersPlugin\DAO\Event' => $pluginsDir . '/SubscribersPlugin/DAO/Event.php',
    'phpList\plugin\SubscribersPlugin\DAO\ListSubscription' => $pluginsDir . '/SubscribersPlugin/DAO/ListSubscription.php',
    'phpList\plugin\SubscribersPlugin\DAO\Subscriptions' => $pluginsDir . '/SubscribersPlugin/DAO/Subscriptions.php',
    'phpList\plugin\SubscribersPlugin\DAO\User' => $pluginsDir . '/SubscribersPlugin/DAO/User.php',
    'phpList\plugin\SubscribersPlugin\InactivePopulator' => $pluginsDir . '/SubscribersPlugin/InactivePopulator.php',
    'phpList\plugin\SubscribersPlugin\ListSubscription' => $pluginsDir . '/SubscribersPlugin/ListSubscription.php',
    'phpList\plugin\SubscribersPlugin\Model\Command' => $pluginsDir . '/SubscribersPlugin/Model/Command.php',
    'phpList\plugin\SubscribersPlugin\Model\Details' => $pluginsDir . '/SubscribersPlugin/Model/Details.php',
    'phpList\plugin\SubscribersPlugin\Model\History' => $pluginsDir . '/SubscribersPlugin/Model/History.php',
    'phpList\plugin\SubscribersPlugin\Model\Subscriptions' => $pluginsDir . '/SubscribersPlugin/Model/Subscriptions.php',
    'phpList\plugin\SubscribersPlugin\PageactionController' => $pluginsDir . '/SubscribersPlugin/pageaction.php',
    'phpList\plugin\SubscribersPlugin\ReportFactory' => $pluginsDir . '/SubscribersPlugin/ReportFactory.php',
    'phpList\plugin\SubscribersPlugin\Report\AbstractReport' => $pluginsDir . '/SubscribersPlugin/Report/AbstractReport.php',
    'phpList\plugin\SubscribersPlugin\Report\Bounce' => $pluginsDir . '/SubscribersPlugin/Report/Bounce.php',
    'phpList\plugin\SubscribersPlugin\Report\Consecutive' => $pluginsDir . '/SubscribersPlugin/Report/Consecutive.php',
    'phpList\plugin\SubscribersPlugin\Report\Domainsubscribers' => $pluginsDir . '/SubscribersPlugin/Report/Domainsubscribers.php',
    'phpList\plugin\SubscribersPlugin\Report\Invalid' => $pluginsDir . '/SubscribersPlugin/Report/Invalid.php',
    'phpList\plugin\SubscribersPlugin\Report\Nolist' => $pluginsDir . '/SubscribersPlugin/Report/Nolist.php',
    'phpList\plugin\SubscribersPlugin\Report\Notconfirmed' => $pluginsDir . '/SubscribersPlugin/Report/Notconfirmed.php',
    'phpList\plugin\SubscribersPlugin\Report\Unsubscribereason' => $pluginsDir . '/SubscribersPlugin/Report/Unsubscribereason.php',
    'phpList\plugin\SubscribersPlugin\SubscriberPopulator' => $pluginsDir . '/SubscribersPlugin/SubscriberPopulator.php',
];
